/**
 * 盤面表示字 → canonical pieceCode（未成り）。
 * `piece-conversion` / 手駒解決 / SFEN などで共有する。ここは game-rules からも参照するため
 * game-rules や piece-conversion に依存しない。
 */

/** 未成り漢字 → canonical。`竜` は小竜駒（飛の成りの「龍」「竜王」と別物）。 */
export const CHAR_TO_CODE: Readonly<Record<string, string>> = {
  歩: 'FU',
  香: 'KY',
  桂: 'KE',
  銀: 'GI',
  金: 'KI',
  角: 'KA',
  飛: 'HI',
  王: 'OU',
  玉: 'OU',
  忍: 'NIN',
  影: 'KAG',
  砲: 'HOU',
  /** 小竜（`PROMOTED_CODE_TO_CHAR.HI` の「龍」＝竜王とは別駒） */
  竜: 'RYU',
  鳳: 'HOO',
  炎: 'ENN',
  火: 'FIR',
  水: 'SUI',
  波: 'NAM',
  木: 'MOK',
  葉: 'HAA',
  光: 'HIK',
  星: 'HOS',
  闇: 'YAM',
  魔: 'MAK',
  銅: 'COPPER',
  鉄: 'IRON',
  錫: 'TIN',
  鉛: 'LEAD',
  宝: 'TREASURE',
  電: 'ELECTRIC',
  雷: 'THUNDER',
  時: 'TIME',
  氷: 'ICE',
  雪: 'SNOW',
  砂: 'SAND',
  風: 'WIND',
  苔: 'MOSS',
  魚: 'FISH',
  雲: 'CLOUD',
  虹: 'RAINBOW',
  毒: 'POISON',
  沼: 'SWAMP',
  牢: 'PRISON',
  柵: 'FENCE',
  嶺: 'RIDGE',
  峰: 'PEAK',
  山: 'YAMA',
  岩: 'ROCK',
  鉱: 'ORE',
  墓: 'GRAVE',
  霊: 'SPIRIT',
  幻: 'PHANTOM',
  霧: 'MIST',
  月: 'MOON',
  舟: 'BOAT',
  機: 'MACHINE',
  歯: 'GEAR',
  家: 'HOUSE',
  民: 'PEOPLE',
  畑: 'FIELD',
  泉: 'SPRING',
  辰: 'TATSU',
  実: 'EXPERIMENT',
  異: 'MUTANT',
  K: 'KBOSS',
  轟: 'BIGNOISE',
  犇: 'BULL',
  礼: 'RITUAL',
  聖: 'SAINT',
  悟: 'SATORI',
  心: 'HEART',
  鬱: 'DEPRESSION',
  乙: 'OTSU',
  薔: 'ROSE',
  菊: 'CHRYSANTHEMUM',
  桜: 'CHERRY',
  室: 'GACHA_SHITSU',
  定: 'GACHA_SADAME',
  安: 'GACHA_AN',
  宋: 'GACHA_SO',
  爆: 'GACHA_BAKU',
  煽: 'GACHA_AORI',
  灯: 'GACHA_TOU',
  辺: 'GACHA_HEN',
  逸: 'GACHA_ITSU',
  進: 'GACHA_SHIN',
  逃: 'GACHA_TOU2',
  艸: 'GACHA_SOU',
  閹: 'GACHA_EN',
  膠: 'GACHA_KOU',
  凹: 'CONCAVE',
  凸: 'CONVEX',
  焼: 'SEAR',
  炒: 'SAUTE',
  煮: 'STEW',
  陽: 'YANG',
  陰: 'YIN',
  牛: 'COW',
  豚: 'PIG',
  鶏: 'CHICKEN',
  /** `lib/piece-image-registry` piece_eacc7f540399 / piece_7fc715661514 と整合 */
  銭: 'SEN',
  財: 'ZAI',
  /** `lib/piece-image-registry` piece_c4aeb81f3634 と整合（2×2 占有駒） */
  巨: 'GIANT',
  /** ショップ駒 */
  鳴: 'NAKU',
  走: 'SO',
  種: 'TANE',
  麒: 'KIRIN',
  舞: 'MAI',
  P: 'SHOP_P',
  赤鬼: 'REDONI',
  青鬼: 'BLUEONI',
  黒鬼: 'BLACKONI',
  /** 刀／剣／銃／鎧／盾は載せない（`piecesFromBoardState` の canonical 寄せ用）。手駒は `game-rules` の CAPTURE_CHAR_TO_HAND_CODE。 */
};
