/** matching_server の ported-skill-piece-code と同じ正規化（オンライン同期用） */

import { normalizeGachaSkillPieceCode } from '@/lib/matching-server/gacha-piece-code';

const PORTED_SKILL_CODES = [
  'FLAME',
  'ENN',
  'FIRE',
  'FIR',
  'TREASURE',
  'SUI',
  'WATER',
  'IRON',
  'WAVE',
  'NAM',
  'SAND',
  'BOAT',
  'BIRD',
  'WIND',
  'FISH',
  'MOSS',
  'RAINBOW',
  'BLUEONI',
  'SWAMP',
  'POISON',
  'WATERFALL',
  'A',
  'EXPERIMENT',
  'TIN',
  'ELECTRIC',
  'THUNDER',
  'TIME',
  'BEAST',
  'CLOUD',
  'MIST',
  'PHANTOM',
  'HOUSE',
  'FIELD',
  'PEOPLE',
  'MIRROR',
  'MOON',
  'MACHINE',
  'GEAR',
  'KATANA',
  'GUN',
  'ARMOR',
  'BOOK',
  'SEAL',
  'RITUAL',
  'SAINT',
  'DISEASE',
  'MEDICINE',
  'HOLE',
  'ABYSS',
  'OBORO',
  'DEATH',
  'SOUL',
  'SATORI',
  'HEART',
  'SEAR',
  'SAUTE',
  'STEW',
  'CONCAVE',
  'CONVEX',
  'YANG',
  'YIN',
  'PIG',
  'CHICKEN',
  'COW',
  'SEN',
  'ZAI',
  'GIANT',
  'HIK',
  'CHERRY',
  'ICE',
  'SNOW',
  'WOOD',
  'MOK',
  'LEAF',
  'HAA',
  'TANE',
  'SHOP_TANE',
  'BULL',
  'BIGNOISE',
  'REDONI',
  'BLACKONI',
  'DEMON',
  'MAK',
  'RYU',
  'SPRING',
  'TATSU',
  'DARK',
  'YAM',
  'PRISON',
  'FENCE',
  'RIDGE',
  'KBOSS',
  'ORE',
  'GRAVE',
  'ROCK',
  'DEPRESSION',
  'ROSE',
  'CHRYSANTHEMUM',
  'PEAK',
  'GACHA_BAKU',
  'GACHA_SHITSU',
  'GACHA_SADAME',
  'GACHA_AN',
  'GACHA_SO',
  'GACHA_TOU',
  'GACHA_HEN',
  'GACHA_ITSU',
  'GACHA_TOU2',
  'GACHA_SOU',
  'GACHA_KOU',
  'GACHA_AORI',
  'MAI',
  'SHOP_MAI',
] as const;

const PORTED_SKILL_CODE_SET = new Set<string>(PORTED_SKILL_CODES);

const CHAR_TO_SKILL_CODE: Readonly<Record<string, string>> = {
  炎: 'ENN',
  火: 'FIR',
  水: 'SUI',
  波: 'NAM',
  木: 'MOK',
  葉: 'HAA',
  種: 'TANE',
  闇: 'YAM',
  魔: 'MAK',
  鉄: 'IRON',
  錫: 'TIN',
  宝: 'TREASURE',
  電: 'ELECTRIC',
  雷: 'THUNDER',
  時: 'TIME',
  獣: 'BEAST',
  雲: 'CLOUD',
  霧: 'MIST',
  幻: 'PHANTOM',
  家: 'HOUSE',
  畑: 'FIELD',
  民: 'PEOPLE',
  鏡: 'MIRROR',
  月: 'MOON',
  機: 'MACHINE',
  歯: 'GEAR',
  刀: 'KATANA',
  銃: 'GUN',
  鎧: 'ARMOR',
  書: 'BOOK',
  封: 'SEAL',
  礼: 'RITUAL',
  聖: 'SAINT',
  病: 'DISEASE',
  薬: 'MEDICINE',
  滝: 'WATERFALL',
  穴: 'HOLE',
  淵: 'ABYSS',
  朧: 'OBORO',
  死: 'DEATH',
  魂: 'SOUL',
  悟: 'SATORI',
  心: 'HEART',
  焼: 'SEAR',
  炒: 'SAUTE',
  煮: 'STEW',
  凹: 'CONCAVE',
  凸: 'CONVEX',
  陽: 'YANG',
  陰: 'YIN',
  豚: 'PIG',
  牛: 'COW',
  鶏: 'CHICKEN',
  銭: 'SEN',
  財: 'ZAI',
  巨: 'GIANT',
  光: 'HIK',
  桜: 'CHERRY',
  氷: 'ICE',
  雪: 'SNOW',
  砂: 'SAND',
  風: 'WIND',
  苔: 'MOSS',
  魚: 'FISH',
  虹: 'RAINBOW',
  毒: 'POISON',
  沼: 'SWAMP',
  牢: 'PRISON',
  柵: 'FENCE',
  嶺: 'RIDGE',
  峰: 'PEAK',
  岩: 'ROCK',
  鉱: 'ORE',
  墓: 'GRAVE',
  鬱: 'DEPRESSION',
  薔: 'ROSE',
  菊: 'CHRYSANTHEMUM',
  辰: 'TATSU',
  竜: 'RYU',
  泉: 'SPRING',
  実: 'EXPERIMENT',
  轟: 'BIGNOISE',
  犇: 'BULL',
  赤鬼: 'REDONI',
  青鬼: 'BLUEONI',
  黒鬼: 'BLACKONI',
  爆: 'GACHA_BAKU',
  室: 'GACHA_SHITSU',
  定: 'GACHA_SADAME',
  安: 'GACHA_AN',
  宋: 'GACHA_SO',
  灯: 'GACHA_TOU',
  辺: 'GACHA_HEN',
  逸: 'GACHA_ITSU',
  逃: 'GACHA_TOU2',
  艸: 'GACHA_SOU',
  膠: 'GACHA_KOU',
  煽: 'GACHA_AORI',
  舞: 'MAI',
  禽: 'BIRD',
  走: 'SHOP_SO',
};

/** BFF instance id の hex 断片 → canonical skill code（game-rules OPAQUE_CAPTURE と整合） */
const OPAQUE_HEX_TO_SKILL_CODE: Readonly<Record<string, string>> = {
  '8CC9287B7E93': 'WATERFALL',
  '29ECAB1EF3C3': 'BIRD',
  '3EFA5702E75B': 'PIG',
  F75D88C48D6D: 'COW',
  '5D848242A136': 'BOOK',
  '7FC715661514': 'ZAI',
  '124C31EA5D7A': 'CHERRY',
  C4AEB81F3634: 'GIANT',
  '6D4AFA9CDF1C': 'SATORI',
  CA16911978FF: 'HEART',
  '0F14ABCC6E5E': 'HOLY_SWORD',
};

function resolveOpaqueHexSkillCode(code: string): string | null {
  for (const [hex, skillCode] of Object.entries(OPAQUE_HEX_TO_SKILL_CODE)) {
    if (code.includes(hex)) return skillCode;
  }
  return null;
}

function stripNamedPiecePrefix(code: string): string {
  const upper = code.trim().toUpperCase();
  if (!upper.startsWith('PIECE_')) return upper;
  if (/^PIECE_[0-9A-F]{8,}$/i.test(upper)) return upper;
  if (upper.startsWith('PIECE_SHOGI_')) return upper.slice('PIECE_SHOGI_'.length);
  return upper.slice('PIECE_'.length);
}

export function normalizeSkillPieceCode(raw: string, char?: string | null): string {
  const fromGacha = normalizeGachaSkillPieceCode(raw, char);
  let code = stripNamedPiecePrefix(fromGacha);

  if (code === 'WATER') return 'SUI';
  if (PORTED_SKILL_CODE_SET.has(code)) return code;
  const fromOpaqueHex = resolveOpaqueHexSkillCode(code);
  if (fromOpaqueHex) return fromOpaqueHex;

  const trimmedChar = char?.trim();
  if (trimmedChar && CHAR_TO_SKILL_CODE[trimmedChar]) {
    return CHAR_TO_SKILL_CODE[trimmedChar];
  }

  return code;
}

/** @deprecated use normalizeSkillPieceCode */
export const normalizeGachaSkillPieceCodeForWire = normalizeGachaSkillPieceCode;
